landscape: 1
short_size: [720, 720]
aspect_ratio: [1, 1]

document:
  fullscreen: 1
  landscape: 1
  short_size: [480, 480]
  aspect_ratio: [1, 1]

  content:
    margin: [0.1, 0.1]
    text:
      path: resources/corpus/note_ko.txt
    font:
      paths: [resources/font/ko]
      weights: [1]
      bold: 0
    layout:
      text_scale: [0.06, 0.06]
      max_row: 7
      max_col: 1
      fill: [0.7, 1]
      full: 0.1
      align: [left, left]
      stack_spacing: [0.0334, 0.0334]
      stack_fill: [1, 1]
      stack_full: 0.1
    textbox:
      fill: [0.3, 1]