landscape: 0.5
short_size: [720, 1024]
aspect_ratio: [1, 2]

document:
  fullscreen: 0.5
  landscape: 0.5
  short_size: [480, 1024]
  aspect_ratio: [1, 2]

  content:
    margin: [0.05, 0.1]
    text:
      path: resources/corpus/note_ko.txt
    font:
      paths: [resources/font/ko]
      weights: [1]
      bold: 0
    layout:
      text_scale: [0.06, 0.07]
      max_row: 10
      max_col: 3
      fill: [0.5, 1]
      full: 0.1
      align: [left, right, center]
      stack_spacing: [0.0334, 0.0334]
      stack_fill: [0.5, 1]
      stack_full: 0.1
    textbox:
      fill: [0.5, 1]